spring:
  banner:
    location: "classpath:banner.txt" 
    charset: UTF-8
  servlet:
    multipart:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 2000

properties:
  aesKey: zeedeco1234!@#$%
    
  
  
    
