spring:
  profiles:
    active: prod
  banner:
    location: "classpath:banner.txt"
    charset: UTF-8
  servlet:
    multipart:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 2000
  error:
    include-exception: true
properties:
  aesKey: kong1234!@#$%Qwe
  
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    display-query-params-without-oauth2: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

api:
  jwt:
    secret: k@ng-backE&D!
    valid-time: 720h
